//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class IndPlanExport : global::System.Configuration.ApplicationSettingsBase {
        
        private static IndPlanExport defaultInstance = ((IndPlanExport)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new IndPlanExport())));
        
        public static IndPlanExport Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int DisciplinesStartRow {
            get {
                return ((int)(this["DisciplinesStartRow"]));
            }
            set {
                this["DisciplinesStartRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26, 6")]
        public global::System.Drawing.Point YearsDescriptionRowCell {
            get {
                return ((global::System.Drawing.Point)(this["YearsDescriptionRowCell"]));
            }
            set {
                this["YearsDescriptionRowCell"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29, 8")]
        public global::System.Drawing.Point TeacherFIORowCell {
            get {
                return ((global::System.Drawing.Point)(this["TeacherFIORowCell"]));
            }
            set {
                this["TeacherFIORowCell"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DisciplineNameColumn {
            get {
                return ((int)(this["DisciplineNameColumn"]));
            }
            set {
                this["DisciplineNameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int DisciplineDescrColumn {
            get {
                return ((int)(this["DisciplineDescrColumn"]));
            }
            set {
                this["DisciplineDescrColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int StudentsCountColumn {
            get {
                return ((int)(this["StudentsCountColumn"]));
            }
            set {
                this["StudentsCountColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int DisciplineSettingsStartColumn {
            get {
                return ((int)(this["DisciplineSettingsStartColumn"]));
            }
            set {
                this["DisciplineSettingsStartColumn"] = value;
            }
        }
    }
}
