//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class SemesterExport : global::System.Configuration.ApplicationSettingsBase {
        
        private static SemesterExport defaultInstance = ((SemesterExport)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SemesterExport())));
        
        public static SemesterExport Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int FITStartRow {
            get {
                return ((int)(this["FITStartRow"]));
            }
            set {
                this["FITStartRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int MSFStartRow {
            get {
                return ((int)(this["MSFStartRow"]));
            }
            set {
                this["MSFStartRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int IDPOStartRow {
            get {
                return ((int)(this["IDPOStartRow"]));
            }
            set {
                this["IDPOStartRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int MAGStartRow {
            get {
                return ((int)(this["MAGStartRow"]));
            }
            set {
                this["MAGStartRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int IndexColumn {
            get {
                return ((int)(this["IndexColumn"]));
            }
            set {
                this["IndexColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int GroupColumn {
            get {
                return ((int)(this["GroupColumn"]));
            }
            set {
                this["GroupColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int CourceColumn {
            get {
                return ((int)(this["CourceColumn"]));
            }
            set {
                this["CourceColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int DisciplineColumn {
            get {
                return ((int)(this["DisciplineColumn"]));
            }
            set {
                this["DisciplineColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int DisciplineCostColumn {
            get {
                return ((int)(this["DisciplineCostColumn"]));
            }
            set {
                this["DisciplineCostColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int LecFactColumn {
            get {
                return ((int)(this["LecFactColumn"]));
            }
            set {
                this["LecFactColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int StudentsColumn {
            get {
                return ((int)(this["StudentsColumn"]));
            }
            set {
                this["StudentsColumn"] = value;
            }
        }
    }
}
